# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem "pg"
#

  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling


  # The specifid database role being used to connect to PostgreSQL.
  # To create additional roles in PostgreSQL see `$ createuser --help`.
  # When left blank, PostgreSQL will use the default role. This is
  # the same nam as the operating system user running Rails.
  #username: power_bank_management_api

  # The password associated with the PostgreSQL role (username).
  #password:

  # Connect on a TCP socket. Omitted by default since the client uses a
  # domain socket that doesn't need configuration. Windows does not have
  # domain sockets, so uncomment these lines.
  #host: localhos

  # The TCP port the server listens on. Defaults to 5432.
  # If your server runs on a different port number, change accordingly.
  #port: 5432

  # Schema search path. The server defalts to $user,public
  #schema_search_path: myapp,sharedapp,public

  # Minimum log levels, in increasing ordebug3, debug2, debug1,
  #   log, notice, warning, error, fatal, and panic
  # Defaults to warning.
  #min_messages: notic
# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this dbto the same as development or production.

#
# Instead, provide thepassword or a full connection URL as an environment
# variable when you boot the app. For example:
#
#   DATABASE_URL="postges://myuser:mypass@localhost/somedatabase"
#
# If the connection URL is provided in the special DATABASE_URL environment
# variable, Rails will a

default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  port: 5432

development:
  <<: *default
  database: power_bank_management_api_development
  username: alpha
  password: '0331'

test:
  <<: *default
  database: power_bank_management_api_test
  username: alpha
  password: '0331'

production:
  <<: *default
  database: power_bank_management_api_production
  username: alpha
  password: '0331'